(load "tests/tests-driver.scm")

(define int_tag_width           2)
(define int_tag                 #b00)
(define bool_tag_width          6)
(define bool_tag                #b101111)
(define empty_list_tag_width    8)
(define empty_list_tag          #b00111111)
(define char_tag_width          8)
(define char_tag                #b00001111)

(define (mask w) 
    (ash #b11111111 (- w 8))
)

(define (empty-list? x) 
    (null? x)
)

(define (immediate? x) 
    (or (integer? x) (boolean? x) (empty-list? x) (char? x))
)

(define (represent x) 
    (cond
        ((integer? x)       (fxlogor int_tag (ash x int_tag_width)))
        ((boolean? x)       (fxlogor bool_tag (ash (if x 1 0) bool_tag_width)))
        ((empty-list? x)    (fxlogor empty_list_tag (ash 0 empty_list_tag_width)))
        ((char? x)          (fxlogor char_tag (ash (char->integer x) char_tag_width)))
    )
)

(define (emit-expr x)
    (emit " movl $~s, %eax" (represent x))
)

(define (emit-program x)
    (unless (immediate? x) (error 'emit "unknow value"))
    (emit " .text")
    (emit " .globl scheme_entry")
    (emit " .type scheme_entry, @function")
    (emit "scheme_entry:")
    (emit-expr x)
    (emit " ret")
    (emit " .size scheme_entry, .-scheme_entry")
)
